
{% set name = "@jupyter_dojo/labextension" %}
{% set version = "0.1.1" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}
{% set sha256 = "4fb63644aa3f49ea35d5e3d714f24e2221aaf4b3177a9298249fbb08680a2d43" %}


package:
  name: jupyterlab_dojo
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - jupyter labextension install {{ name }}-{{ version }}.tgz
    - jupyter lab build

requirements:
  build:
    - jupyterlab >=0.30
    - nodejs {{node_version}}
  run:
    - jupyterlab >=0.30
    - nodejs {{node_version}}

test:
  imports:
    - jupyter_dojo

about:
  home: https://github.com/JoaoFelipe/jupyter-dojo
  license: MIT
  license_family: MIT
  summary: 'Install the coding dojo labextension for ipython_unittest'
  dev_url: https://github.com/JoaoFelipe/ipython-unittest

extra:
  recipe-maintainers:
    - JoaoFelipe
