
{% set conda_package_name = "jupyterlab_dojo" %}
{% set extension_name = "labextension" %}
{% set installed_name = "jupyter_dojo-labextension*.tgz" %}
{% set name = "@jupyter_dojo/labextension" %}
{% set version = "0.1.1" %}
{% set node_version = os.environ.get('NODEJS_VERSION') or '6.*' %}
{% set sha256 = "4fb63644aa3f49ea35d5e3d714f24e2221aaf4b3177a9298249fbb08680a2d43" %}


package:
  name: {{ conda_package_name }}
  version: {{ version }}

source:
  fn: {{ extension_name }}-{{ version }}.tgz
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 4
  script:
    - jupyter labextension install .
    - jupyter lab build

requirements:
  build:
    - jupyterlab >=0.30
    - nodejs {{node_version}}
  run:
    - ipython_unittest >=0.3
    - jupyterlab >=0.30
    - nodejs {{node_version}}

test:
  commands:
    - test -f $PREFIX/share/jupyter/lab/extensions/{{ installed_name }}  # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\lab\\extensions\\{{ installed_name }} # [win]

about:
  home: https://github.com/JoaoFelipe/jupyter-dojo
  license: MIT
  license_family: MIT
  summary: 'Install the coding dojo labextension for ipython_unittest'
  dev_url: https://github.com/JoaoFelipe/ipython-unittest

extra:
  recipe-maintainers:
    - JoaoFelipe
